# -*- coding: utf-8 -*-
"""Case Study 01 EDA - Ganjil 2022 Kelompok 5  .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yGi-QW5o0tsJ2VP8cMkFAgSL5q5nX1Up
"""

import pandas as pd

file_ = 'data/price.cvc'

try: # Running Locally, yakinkan "file_" berada di folder "data"
    dfJ = pd.read_csv("data/jakarta.csv", low_memory = False, encoding='utf8')
    dfD = pd.read_csv("data/depok.csv", low_memory = False, encoding='utf8')
    dfT = pd.read_csv("data/tangerang.csv", low_memory = False, encoding='utf8')
except: # Running in Google Colab
    !mkdir data
    !wget -P data/ https://raw.githubusercontent.com/taufiksutanto/EDA-Case-01-PreProcessing/master/data/jakarta.csv
    !wget -P data/ https://raw.githubusercontent.com/taufiksutanto/EDA-Case-01-PreProcessing/master/data/depok.csv
    !wget -P data/ https://raw.githubusercontent.com/taufiksutanto/EDA-Case-01-PreProcessing/master/data/tangerang.csv
    dfJ = pd.read_csv("data/jakarta.csv", low_memory = False, encoding='utf8')
    dfD = pd.read_csv("data/depok.csv", low_memory = False, encoding='utf8')
    dfT = pd.read_csv("data/tangerang.csv", low_memory = False, encoding='utf8')
    
N, P, Q = dfJ.shape, dfD.shape, dfT.shape
print('baris= ', N, ', kolom (jumlah variable) = ', P)
print("Tipe varian df =", type(dfJ))
dfJ

"""Untuk wilayah Jakarta"""

#
dfJ.drop("sertifikat", axis=1, inplace=True)
dfJ.drop("Unnamed: 14", axis=1, inplace=True)
dfJ.drop("Unnamed: 15", axis=1, inplace=True)
dfJ.drop("Unnamed: 16", axis=1, inplace=True)
dfJ.drop("Unnamed: 17", axis=1, inplace=True)
dfJ.drop("Unnamed: 18", axis=1, inplace=True)
dfJ.drop("Unnamed: 19", axis=1, inplace=True)
dfJ.drop("Unnamed: 20", axis=1, inplace=True)
dfJ.drop("Unnamed: 21", axis=1, inplace=True)
dfJ.drop("Unnamed: 22", axis=1, inplace=True)
dfJ.drop("Unnamed: 23", axis=1, inplace=True)
dfJ.drop("Unnamed: 24", axis=1, inplace=True)
dfJ.drop("Unnamed: 25", axis=1, inplace=True)
dfJ

dfJ.describe()

dfJ.describe(include='all')

"""Untuk wilayah Depok"""

print('baris= ', N, ', kolom (jumlah variable) = ', P)
print("Tipe varian df =", type(dfD))
dfD

dfD.drop("sertifikat", axis=1, inplace=True)
dfD.drop("garasi", axis=1, inplace=True)
dfD.drop("hadap", axis=1, inplace=True)
dfD.drop("Unnamed: 14", axis=1, inplace=True)
dfD.drop("Unnamed: 15", axis=1, inplace=True)
dfD.drop("Unnamed: 16", axis=1, inplace=True)
dfD.drop("Unnamed: 17", axis=1, inplace=True)
dfD.drop("Unnamed: 18", axis=1, inplace=True)
dfD.drop("Unnamed: 19", axis=1, inplace=True)
dfD.drop("Unnamed: 20", axis=1, inplace=True)
dfD.drop("Unnamed: 21", axis=1, inplace=True)
dfD.drop("Unnamed: 22", axis=1, inplace=True)
dfD.drop("Unnamed: 23", axis=1, inplace=True)
dfD.drop("Unnamed: 24", axis=1, inplace=True)
dfD.drop("Unnamed: 25", axis=1, inplace=True)
dfD

dfD.info()

dfD.describe(include='all')

dfD.describe(include='all')

print('baris= ', N, ', kolom (jumlah variable) = ', P)
print("Tipe varian df =", type(dfT))
dfT

dfT.drop("sertifikat", axis=1, inplace=True)
dfT.drop("garasi", axis=1, inplace=True)
dfT.drop("hadap", axis=1, inplace=True)
dfT.drop("Unnamed: 14", axis=1, inplace=True)
dfT.drop("Unnamed: 15", axis=1, inplace=True)
dfT.drop("Unnamed: 16", axis=1, inplace=True)
dfT.drop("Unnamed: 17", axis=1, inplace=True)
dfT.drop("Unnamed: 18", axis=1, inplace=True)
dfT.drop("Unnamed: 19", axis=1, inplace=True)
dfT.drop("Unnamed: 20", axis=1, inplace=True)
dfT.drop("Unnamed: 21", axis=1, inplace=True)
dfT.drop("Unnamed: 22", axis=1, inplace=True)
dfT.drop("Unnamed: 23", axis=1, inplace=True)
dfT.drop("Unnamed: 24", axis=1, inplace=True)
dfT.drop("Unnamed: 25", axis=1, inplace=True)
dfT

"""#dfT (Tangerang)"""

print('baris= ', N, ', kolom (jumlah variable) = ', P)
print("Tipe varian df =", type(dfT))
dfT

dfT.describe()

dfT.describe(include='all')

"""kESIMPULAN:
1. Kualitas data yang dimiliki peruhasan berdasarkan preprosesing data yaitu adanya variabel noise seperti serifikat, garasi, hadap, dan Unnamed 14-25.
2. Agar menjadi data driven company yang unggul, perlu ditambahkan variabel jarak dari rumah ke pintu tol dan rumah sakit yang menjadi kriteria dari sebagian besar orang.
3. berdasarkan statistika deskripif dari ketiga kota, diketa
"""